"""Preflight local assets before attempting Prithvi-WxC inference.

The check is intentionally lightweight. It never downloads the 28.4 GB
checkpoint or the ~401 GB climatology collection and never creates synthetic
statistics. It tells the operator exactly which external assets are missing.
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MERra_DIR = ROOT / "backend" / "data" / "merra2"
DEFAULT_CHECKPOINTS = [
    ROOT / "models" / "prithvi-wxc" / "prithvi.wxc.rollout.2300m.v1.pt",
    ROOT / "models" / "prithvi-wxc" / "prithvi_wxc_rollout.pt",
]
DEFAULT_CLIM_DIR = ROOT / "backend" / "data" / "prithvi_wxc_climatology"


def report(label: str, ok: bool, detail: str) -> None:
    print(f"[{ 'PASS' if ok else 'WAIT' }] {label}: {detail}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path)
    parser.add_argument("--climatology-dir", type=Path, default=DEFAULT_CLIM_DIR)
    parser.add_argument("--merra2-dir", type=Path, default=MERra_DIR)
    args = parser.parse_args()

    checkpoint = args.checkpoint
    if checkpoint is None:
        checkpoint = next((p for p in DEFAULT_CHECKPOINTS if p.exists()), DEFAULT_CHECKPOINTS[0])

    merra_files = sorted(args.merra2_dir.glob("*.nc")) + sorted((args.merra2_dir / "prepared").glob("*.nc"))
    clim_files = sorted(args.climatology_dir.glob("*.nc")) if args.climatology_dir.exists() else []

    print("=" * 70)
    print("PRITHVI-WxC ASSET PREFLIGHT")
    print("=" * 70)
    report("MERRA-2 input", bool(merra_files), f"{len(merra_files)} NetCDF file(s) found")
    report("Checkpoint", checkpoint.exists(), str(checkpoint))
    report("Official climatology", bool(clim_files), f"{len(clim_files)} NetCDF file(s) found in {args.climatology_dir}")
    print("-" * 70)
    print("The official rollout checkpoint is ~28.4 GB; the full climatology collection is ~401 GB.")
    print("These assets are intentionally external to normal Git/Codespace storage.")
    print("No synthetic normalization/statistics will be generated by this project.")
    print("=" * 70)

    ready = bool(merra_files and checkpoint.exists() and clim_files)
    print(f"READY FOR INFERENCE: {ready}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
